{% set name = "cmake-format" %}
{% set version = "0.6.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cheshirekow/cmake_format/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b67dd150380d9223036a12f82126a7a9b18e77db4a8d7240f993ee090884e4bf

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} setup.py bdist_wheel
    - {{ PYTHON }} -m pip install dist/*.whl
  entry_points:
    - cmake-annotate = cmakelang.annotate:main
    - cmake-format = cmakelang.format.__main__:main
    - cmake-lint = cmakelang.lint.__main__:main
    - cmake-genparsers = cmakelang.genparsers:main
    - ctest-to=cmakelang.ctest_to:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - six >=1.13.0
    - pyyaml >=5.3
    - jinja2 >=2.10.3

test:
  imports:
    - cmakelang
  commands:
    - cmake-format -h
    - cmake-lint -h
    - cmake-annotate -h
    - cmake-genparsers -h
    - ctest-to -h

about:
  home: https://github.com/cheshirekow/cmake_format
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Source code formatter for cmake listfiles

  description: |
    The cmake-format project provides Quality Assurance (QA) tools for cmake.
    * cmake-annotate can generate pretty HTML from your listfiles
    * cmake-format can format your listfiles nicely so that they don't
      look like crap.
    * cmake-lint can check your listfiles for problems
    * ctest-to can parse a ctest output tree and translate it into a more
      structured format (either JSON or XML).
  doc_url: https://cmake-format.readthedocs.io/
  dev_url: https://github.com/cheshirekow/cmake_format

extra:
  recipe-maintainers:
    - avrahamshukron
    - xhochy
